name: document_scanner
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.0.6 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  camera: ^0.10.5+5
  image_picker: ^1.0.4
  path_provider: ^2.1.1
  simple_edge_detection:
    path: ../simple_edge_detection/
  flutter_screenutil: ^5.9.0
  path: ^1.8.3
  intl: ^0.18.1
  google_fonts: ^6.1.0
  google_mlkit_text_recognition: ^0.8.1
  image: ^4.1.3

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

